services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./static:/static
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build: ./server
    ports:
      - "1111:3000"
    environment:
      - PORT=1111

  server2:
    build: ./server
    ports:
      - "2222:3000"
    environment:
      - PORT=2222

  server3:
    build: ./server
    ports:
      - "3333:3000"
    environment:
      - PORT=3333 